### ISSUE TITLE
Release in crates

### ISSUE THREAD

**Issue by octplane** [llambda/rust-reverse-geocoder#4]
Hello,

could it be possible for you to release the "api" to crates.io?

Thanks for your code!

**Comment by gx0r** [comment]
That would be nice. I haven't had time yet, unfortunately, but feel free to submit a PR!

**Comment by naturallymitchell** [comment]
> ...feel free to submit a PR

It's something only you can do.  It'll only take a couple min: [Publishing on crates.io](https://doc.rust-lang.org/cargo/reference/publishing.html).

**Comment by teovoinea** [comment]
Hi @llambda, just wanted to bring this back up. Like @naturallymitchell said it only takes a couple minutes to publish to crates.io. It's blocking other crates that want to publish because you [can't publish crates that depend on crates from git repos](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories).

All you need is `cargo login {YOUR_KEY}` and `cargo publish` 😄

**Comment by gx0r** [comment]
Thanks, I will do that, and I was not aware other crates were wanting to publish based off this.

**Comment by llambda** [comment]
Published, thanks for suggesting it. If you happen to use this software I'd love to hear about your use just out of my own curiosity, feel free to ping me a line on this issue, xxgsoftware@gmail.com or keybase.

**Comment by teovoinea** [comment]
I'm using it in my podium project: https://github.com/teovoinea/podium

In the interest of privacy I wanted an offline reverse geocoder for location metadata found in images.

**Comment by gx0r** [comment]
Released:

- https://crates.io/crates/reverse_geocoder/1.0.1 with existing API
- https://crates.io/crates/reverse_geocoder/2.0.0-alpha.0 with improved API
